### PR TITLE
TEST: new structure to support annotation

### PR DESCRIPTION
**Pull request by mazipan**
Closes: #72, #73, #76

## What is the current behavior?

Bunch of improvement in E2E

- [x] Add new projects for mobile web testing
- [x] Separate desktop & mobile test using annotation and file name postfix to grep the projects
- [x] Tidy up the test scenario by leveraging the `test.steps`

## What is the new behavior?

Now you can either run all tests (desktop & mobile), using existing command (`npm run test:e2e`) or select by group `test:e2e:desktop` or `test:e2e:mobile`.

Currently, I try to split the desktop and mobile by using the filename `.desktop.spec.ts` for desktop, and `.mobile.spec.ts` for mobile. I still can not figure out how to filter it out by using the annotation only.

## Report

Screenshot 2024-12-02 at 15 45 48
Screenshot 2024-12-02 at 15 45 55

### CODE REVIEW

**Comment by mazipan** [comment]
I do also think of that.
Since not of all of test cases are different between browser.

I will update the implementation tomorrow and let you know.

**Comment by mazipan** [comment]
Previously I don't know how to skip some test from certain browser 😂

That's why the easiest one is by separating the test case.

**Comment by mazipan** [comment]
FIXED ya @depapp.

Now we can share the test case between desktop & mobile.

If we have different test case, we can use `test.skip` and using `isMobile` to determine the browser type since we use same BrowserName (chromium) for both desktop & mobile.

**Review by depapp — APPROVED** [review]
thank you mas @mazipan 🙇🏻

**Pull request merged**
